/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    dogs: Dog;
    dogbreeds: Dogbreed;
    pages: Page;
    posts: Post;
    coatColors: CoatColor;
    coatTypes: CoatType;
    tags: Tag;
    countries: Country;
    roles: Role;
    fciGroups: FciGroup;
    fciSections: FciSection;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    media: {
      linkedDogbreeds: 'dogbreeds';
    };
    coatColors: {
      linkedDogbreeds: 'dogbreeds';
    };
    coatTypes: {
      linkedDogbreeds: 'dogbreeds';
    };
    tags: {
      linkedDogbreeds: 'dogbreeds';
    };
    countries: {
      linkedDogbreeds: 'dogbreeds';
    };
    roles: {
      linkedDogbreeds: 'dogbreeds';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    dogs: DogsSelect<false> | DogsSelect<true>;
    dogbreeds: DogbreedsSelect<false> | DogbreedsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    coatColors: CoatColorsSelect<false> | CoatColorsSelect<true>;
    coatTypes: CoatTypesSelect<false> | CoatTypesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    fciGroups: FciGroupsSelect<false> | FciGroupsSelect<true>;
    fciSections: FciSectionsSelect<false> | FciSectionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  source?: string | null;
  dogbreeds?: (number | Dogbreed)[] | null;
  linkedDogbreeds?: {
    docs?: (number | Dogbreed)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dogbreeds".
 */
export interface Dogbreed {
  id: number;
  /**
   * Gib hier die offizielle Bezeichnung der Rasse ein.
   */
  breed: string;
  /**
   * Der Slug wird automatisch aus dem Namen der Hunderasse generiert.
   */
  slug?: string | null;
  /**
   * Steuert, ob die Rasse auf der Website angezeigt wird und ob sie vollständig ist.
   */
  status: 'draft' | 'published' | 'partial';
  general?: {
    /**
     * Trage hier zusätzliche Namen ein, unter denen die Rasse bekannt ist. Bestätige einen Namen mit Enter.
     */
    otherNames?: string[] | null;
    /**
     * Schlagworte, z. B. Eigenschaften oder typische Nutzung.
     */
    tags?: (number | Tag)[] | null;
    /**
     * Aktivieren, wenn es sich um eine Hybrid- oder Mischlingsrasse handelt.
     */
    isHybrid?: boolean | null;
    /**
     * Typische Rassen, die für diese Hybridrasse kombiniert wurden.
     */
    parentBreeds?: (number | Dogbreed)[] | null;
    /**
     * Aktivieren, wenn dies eine Variante einer bestehenden Hunderasse ist.
     */
    isVariant?: boolean | null;
    /**
     * Wähle die Hauptrasse, von der diese Variante abstammt.
     */
    mainBreeds?: (number | null) | Dogbreed;
    /**
     * Wähle die bekannten Varianten dieser Hunderasse, falls vorhanden.
     */
    variantBreeds?: (number | Dogbreed)[] | null;
  };
  images?:
    | {
        /**
         * Wähle ein Bild aus der Media-Collection.
         */
        media: number | Media;
        /**
         * Wähle aus, ob das Bild als Thumbnail oder in der Galerie angezeigt werden soll.
         */
        type: 'thumbnail' | 'gallery';
        id?: string | null;
      }[]
    | null;
  fci?: {
    /**
     * Wähle den FCI-Status der Rasse. Wenn "Nicht anerkannt" ausgewählt wird, bleiben die übrigen FCI-Felder ausgeblendet, da diese Informationen nur für anerkannte oder provisorisch anerkannte Rassen relevant sind.
     */
    fciStatus?: ('recognized' | 'provisional' | 'not_recognized') | null;
    /**
     * Die offizielle FCI-Gruppe, zu der die Rasse gehört.
     */
    fciGroup?: (number | null) | FciGroup;
    /**
     * Die Sektion innerhalb der FCI-Gruppe, passend zur Rasse.
     */
    fciSection?: (number | null) | FciSection;
    /**
     * Trage hier das Datum ein, andem die Rasse durch FCI anerkannt wurde
     */
    fciAcceptanceDate?: string | null;
    /**
     * Trage hier das Datum ein, von der Publikation des gültigen offiziellen Standards
     */
    fciPublicationDate?: string | null;
    /**
     * Trage hier den Link zur Rasse ein.
     */
    fciSource?: string | null;
    /**
     * Trage hier den Link zum PDF des offiziellen Standard ein.
     */
    fciSourcePDF?: string | null;
  };
  details?: {
    /**
     * Durchschnittliches Gewicht einer Hündin in kg.
     */
    'weight-female'?: string | null;
    /**
     * Durchschnittliches Gewicht eines Rüden in kg.
     */
    'weight-male'?: string | null;
    /**
     * Durchschnittliche Widerristhöhe einer Hündin in cm.
     */
    'height-female'?: string | null;
    /**
     * Durchschnittliche Widerristhöhe eines Rüden in cm.
     */
    'height-male'?: string | null;
    /**
     * Durchschnittliche Lebenserwartung einer Hündin in Jahren.
     */
    'age-female'?: string | null;
    /**
     * Durchschnittliche Lebenserwartung eines Rüden in Jahren.
     */
    'age-male'?: string | null;
    /**
     * Typische Fellfarben der Rasse. Mehrfachauswahl möglich.
     */
    coatColors?: (number | CoatColor)[] | null;
    /**
     * Kurz, mittellang oder lang – charakteristisch für die Rasse.
     */
    coatTypes?: (number | CoatType)[] | null;
    /**
     * Z. B. Jagdhund, Rettungshund, Therapiehund. Mehrfachauswahl möglich.
     */
    roles?: (number | Role)[] | null;
    /**
     * Land oder Region, aus der die Rasse ursprünglich stammt.
     */
    origin?: (number | null) | Country;
  };
  descriptions?:
    | {
        title: string;
        content: string;
        /**
         * Optional: Quelle angeben, z. B. FCI PDF, Wikipedia, Zuchtverein
         */
        source?: string | null;
        id?: string | null;
      }[]
    | null;
  breeders?:
    | {
        name: string;
        location?: string | null;
        website?: string | null;
        contact?: string | null;
        id?: string | null;
      }[]
    | null;
  influencers?:
    | {
        name: string;
        platform?: ('instagram' | 'tiktok' | 'youtube' | 'other') | null;
        link?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  category?: ('size' | 'training' | 'character' | 'social' | 'health' | 'roles' | 'behavior') | null;
  dogbreeds?: (number | Dogbreed)[] | null;
  linkedDogbreeds?: {
    docs?: (number | Dogbreed)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fciGroups".
 */
export interface FciGroup {
  id: number;
  name: string;
  number: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fciSections".
 */
export interface FciSection {
  id: number;
  name: string;
  number: number;
  group: number | FciGroup;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coatColors".
 */
export interface CoatColor {
  id: number;
  name: string;
  colorCode?: string[] | null;
  group?: ('solid' | 'multi' | 'pattern') | null;
  dogbreeds?: (number | Dogbreed)[] | null;
  linkedDogbreeds?: {
    docs?: (number | Dogbreed)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coatTypes".
 */
export interface CoatType {
  id: number;
  name: string;
  value: string;
  description?: string | null;
  dogbreeds?: (number | Dogbreed)[] | null;
  linkedDogbreeds?: {
    docs?: (number | Dogbreed)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  name: string;
  value: string;
  description?: string | null;
  trainingRequirements?:
    | {
        requirement: string;
        importance?: ('low' | 'medium' | 'high') | null;
        id?: string | null;
      }[]
    | null;
  dogbreeds?: (number | Dogbreed)[] | null;
  linkedDogbreeds?: {
    docs?: (number | Dogbreed)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  continent?: ('europe' | 'asia' | 'africa' | 'north_america' | 'south_america' | 'oceania') | null;
  dogbreeds?: (number | Dogbreed)[] | null;
  linkedDogbreeds?: {
    docs?: (number | Dogbreed)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dogs".
 */
export interface Dog {
  id: number;
  name: string;
  /**
   * Der Slug wird automatisch aus dem Namen des Hundes generiert.
   */
  slug?: string | null;
  images?:
    | {
        /**
         * Wähle ein Bild aus der Media-Collection.
         */
        media: number | Media;
        /**
         * Wähle aus, ob das Bild als Thumbnail oder in der Galerie angezeigt werden soll.
         */
        type: 'thumbnail' | 'gallery';
        id?: string | null;
      }[]
    | null;
  gender?: ('female' | 'male') | null;
  castration?: ('yes' | 'tooYoung' | 'no') | null;
  /**
   * Trage hier weitere Infos zur Kastration.
   */
  castrationInfo?: string | null;
  adoptionStatus?: ('available' | 'reserved' | 'adopted') | null;
  adoptionDate?: string | null;
  location: string;
  locationType?: ('fosterHome' | 'shelter' | 'euthanasiaCenter') | null;
  earliestArrivalType?: ('fixed' | 'estimated' | 'unknown') | null;
  /**
   * Ab diesem Datum ist eine Ausreise nach Deutschland frühestens möglich.
   */
  earliestArrivalDate?: string | null;
  birthDate?: string | null;
  birthDateType?: ('exact' | 'estimated' | 'unknown') | null;
  /**
   * Wähle mehrere Rassen, wenn nötig.
   */
  breeds?: (number | Dogbreed)[] | null;
  breedType?: ('known' | 'estimated' | 'unknown') | null;
  description?: Content[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Content".
 */
export interface Content {
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug?: string | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  hideBreadcrumps?: boolean | null;
  content?: (Content | Hero)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero".
 */
export interface Hero {
  variant: 'stacked' | 'split' | 'imageBackground';
  /**
   * Dieser Text wird oberhalb der Überschrift ausgegeben
   */
  eyebrow?: string | null;
  /**
   * Dies wird die H1 auf der Seite sein. Denk dran, es sollte immer nur eine H1 pro Seite geben
   */
  headline: string;
  text?: string | null;
  ctas?:
    | {
        label: string;
        type: 'intern' | 'extern';
        intern?: (number | null) | Page;
        extern?: string | null;
        style?: ('btn-primary' | 'btn-primary btn-outline' | 'btn-link') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Wird je nach Variante unterschiedlich dargestellt
   */
  image?: (number | null) | Media;
  backgroundColor?:
    | (
        | 'var(--frontend-general)'
        | 'var(--frontend-primary)'
        | 'var(--frontend-secondary)'
        | 'var(--frontend-base-200)'
        | 'var(--frontend-neutral)'
      )
    | null;
  textPosition?: ('left' | 'right' | 'center') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug?: string | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  heroImage?: (number | null) | Media;
  content?: (Hero | Content)[] | null;
  relatedBreeds?: (number | Dogbreed)[] | null;
  sources?:
    | {
        label: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'dogs';
        value: number | Dog;
      } | null)
    | ({
        relationTo: 'dogbreeds';
        value: number | Dogbreed;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'coatColors';
        value: number | CoatColor;
      } | null)
    | ({
        relationTo: 'coatTypes';
        value: number | CoatType;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'fciGroups';
        value: number | FciGroup;
      } | null)
    | ({
        relationTo: 'fciSections';
        value: number | FciSection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  source?: T;
  dogbreeds?: T;
  linkedDogbreeds?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dogs_select".
 */
export interface DogsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  images?:
    | T
    | {
        media?: T;
        type?: T;
        id?: T;
      };
  gender?: T;
  castration?: T;
  castrationInfo?: T;
  adoptionStatus?: T;
  adoptionDate?: T;
  location?: T;
  locationType?: T;
  earliestArrivalType?: T;
  earliestArrivalDate?: T;
  birthDate?: T;
  birthDateType?: T;
  breeds?: T;
  breedType?: T;
  description?:
    | T
    | {
        content?: T | ContentSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Content_select".
 */
export interface ContentSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dogbreeds_select".
 */
export interface DogbreedsSelect<T extends boolean = true> {
  breed?: T;
  slug?: T;
  status?: T;
  general?:
    | T
    | {
        otherNames?: T;
        tags?: T;
        isHybrid?: T;
        parentBreeds?: T;
        isVariant?: T;
        mainBreeds?: T;
        variantBreeds?: T;
      };
  images?:
    | T
    | {
        media?: T;
        type?: T;
        id?: T;
      };
  fci?:
    | T
    | {
        fciStatus?: T;
        fciGroup?: T;
        fciSection?: T;
        fciAcceptanceDate?: T;
        fciPublicationDate?: T;
        fciSource?: T;
        fciSourcePDF?: T;
      };
  details?:
    | T
    | {
        'weight-female'?: T;
        'weight-male'?: T;
        'height-female'?: T;
        'height-male'?: T;
        'age-female'?: T;
        'age-male'?: T;
        coatColors?: T;
        coatTypes?: T;
        roles?: T;
        origin?: T;
      };
  descriptions?:
    | T
    | {
        title?: T;
        content?: T;
        source?: T;
        id?: T;
      };
  breeders?:
    | T
    | {
        name?: T;
        location?: T;
        website?: T;
        contact?: T;
        id?: T;
      };
  influencers?:
    | T
    | {
        name?: T;
        platform?: T;
        link?: T;
        notes?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  hideBreadcrumps?: T;
  content?:
    | T
    | {
        content?: T | ContentSelect<T>;
        hero?: T | HeroSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  headline?: T;
  text?: T;
  ctas?:
    | T
    | {
        label?: T;
        type?: T;
        intern?: T;
        extern?: T;
        style?: T;
        id?: T;
      };
  image?: T;
  backgroundColor?: T;
  textPosition?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  heroImage?: T;
  content?:
    | T
    | {
        hero?: T | HeroSelect<T>;
        content?: T | ContentSelect<T>;
      };
  relatedBreeds?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coatColors_select".
 */
export interface CoatColorsSelect<T extends boolean = true> {
  name?: T;
  colorCode?: T;
  group?: T;
  dogbreeds?: T;
  linkedDogbreeds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coatTypes_select".
 */
export interface CoatTypesSelect<T extends boolean = true> {
  name?: T;
  value?: T;
  description?: T;
  dogbreeds?: T;
  linkedDogbreeds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  dogbreeds?: T;
  linkedDogbreeds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  continent?: T;
  dogbreeds?: T;
  linkedDogbreeds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  value?: T;
  description?: T;
  trainingRequirements?:
    | T
    | {
        requirement?: T;
        importance?: T;
        id?: T;
      };
  dogbreeds?: T;
  linkedDogbreeds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fciGroups_select".
 */
export interface FciGroupsSelect<T extends boolean = true> {
  name?: T;
  number?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fciSections_select".
 */
export interface FciSectionsSelect<T extends boolean = true> {
  name?: T;
  number?: T;
  group?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  lightModeIcon?: (number | null) | Media;
  lightModeLogo?: (number | null) | Media;
  darkModeIcon?: (number | null) | Media;
  darkModeLogo?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  lightModeIcon?: T;
  lightModeLogo?: T;
  darkModeIcon?: T;
  darkModeLogo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}